create table IF NOT EXISTS phones (
    id bigint generated by default as identity,
    city_code varchar(255),
    country_code varchar(255),
    number varchar(255),
    user_id varchar(255),
    primary key (id)
);

create table IF NOT EXISTS tokens (
    uuid varchar(255) not null,
    jwt_token varchar(255),
    primary key (uuid)
);

create table IF NOT EXISTS users (
    user_id varchar(255) not null,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (user_id)
);